{% set version = "0.11.4" %}
package:
  name: matplotlib-venn
  version: {{ version }}

source:
  fn: matplotlib-venn-{{ version }}.zip
  url: https://pypi.io/packages/source/m/matplotlib-venn/matplotlib-venn-{{ version }}.zip
  sha256: 707d66f923f4c75370c78193b80cc2bd7e417ab149d0373d64d677cc4813f391

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - numpy
    - scipy

  run:
    - python
    - matplotlib
    - numpy
    - scipy

test:
  imports:
    - matplotlib_venn

  requires:
    - pytest

about:
  home: https://github.com/konstantint/matplotlib-venn
  license: MIT License
  summary: 'Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.'

extra:
  recipe-maintainers:
    - pmlandwehr
