{% set name = "matplotlib-venn" %}
{% set version = "1.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/konstantint/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6111d8463101e1fe1c567a12d0fa8fff4315ce9acddcbbc5f0915d85d49cb019

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy
  run_constrained:
    - shapely

test:
  source_files:
    - tests
  imports:
    - matplotlib_venn
  commands:
    - pip check
    - pytest -v .
  requires:
    - pip
    - pytest

about:
  home: https://github.com/konstantint/matplotlib-venn
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.
  description: |
    Routines for plotting area-weighted two- and three-circle venn diagrams.
  dev_url: https://github.com/konstantint/matplotlib-venn
  doc_url: https://github.com/konstantint/matplotlib-venn

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
