{% set version = "0.11.10" %}

package:
  name: matplotlib-venn
  version: {{ version }}

source:
  url: https://github.com/konstantint/matplotlib-venn/archive/refs/tags/{{ version }}.tar.gz
  sha256: acb254f6fc0c8eb4e49df6655b316903d6babe2e9c0049636c2426a3a861cfbc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy

test:
  source_files:
    - tests
  imports:
    - matplotlib_venn
  commands:
    - pip check
    - pytest -v . -k "not test_circle_region"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/konstantint/matplotlib-venn
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Functions for plotting area-proportional two- and three-way Venn diagrams in matplotlib.
  description: |
    Routines for plotting area-weighted two- and three-circle venn diagrams.
  dev_url: https://github.com/konstantint/matplotlib-venn
  doc_url: https://github.com/konstantint/matplotlib-venn

extra:
  recipe-maintainers:
    - pmlandwehr
