travis:
  secure:
    BINSTAR_TOKEN: Cy+pxoSaPhvOBFHsTfA5IIZu8rdyJhZzVBiY8g/s6PQehYDHGK5qqaiIuYuUYuwIzLFgE1jt6J+gMrFrmClOBFVDNofLQ/m3LZGWP0IDIsAS4kvM7Z5eqkcsEZfRcRB7XYStiDmKVeqWS1T5d6wtAy9rmHRk2duOZFlOq+RlPLdTqsblhybLC5UYpvV58If87s9VJCbydtR8CrsPFbd1353i+3QaCGJwxe3qgch9ygati/rumILyJLF7umhy5RnR6Qwjt/sMmXk4zvTU06Lix53Qec3WCK5DJPM6PnfEiFdxu6x3AOcedULR/dgwsfqiVfPnPa1oZQmyaljyh8Yu5opqpKMSVrPhj24MZMkCFL1aJEKlsc+Yyqxjs74VV7iewWWFPf2sHH3ok7U74OT8Lxb9oQib9bDyTFuW55o850mglogZmNrUtyQvJkDcwUX8wn3qAVi0gyUnUZEhxvuxlNzB2LPDvOwtYQb1n0zD34EHd5d0VgcuBvZ5IIxg/b8VQsIJMPjjB978xPhVBsg6XF9GN2XLs7WTq5OoHG+3PTHyTullVUdfIAqjmQSYTeGikAtbG44rzdYGshU9D5U2EuWMRLQ81rex3NKD5ftC0F9Hbf9d31Gt3FjkiSajhtXU0a7m8sxb2Pm9fX8WCJ5J7YQSdy6QBA6eqigziJYbLPY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
