travis:
  secure:
    BINSTAR_TOKEN: KvLzkNbJj1osKOY/uCIiu5FWRYKlg3XbnR0SwBzo17oUVTGav9Rv0t7qb0XH/WtiuL4fZTABVOAaCnV19HglzJH5YfBpssRwofTcjagpGgelJwLg9KH+doeOPL744E/D7SGXXMy22h3ObMq37FEbmoUrt2B//s1VU/2Ck6zUYApxDIXxne8YPf2IhNoHpov/xU1f/1L4ziwJJkLSbvKTewW6+2tjH8gcYValWNkfxIUB0l8GXQFKO/PEr8QEFMDmmo+VdoJcN7aVXn5KKs/gO5Q+zgqWXIXB2duD8C3FkYCo9fYsAbdcFH5mttdgusLCgUtCPSArglQdeIZJgVsCaNSFCOsx9gCp8D0b2t1yWrer05jhOJnbgEh1TlPx8PWWA2O7sZtawZB2fHjkgoYK/6s0OBaCBHbl856DUYWGPok/dXjcRCblIaZfiIc7jgd7ao1Xu4Ac7ryPsz++MOFjvLGpmKQPoay+mYVWof5wXzzcrr+jLhQGP33qv+P+EblRG245pXtOz9Q9hgWmKUYeuK8P+0WQYCQZEUlhkvNexUEJmY7zWKdGk3LrAZLRGF9GASiQzU9ZZ1NtGSZyTIagoPVyCJBSzfC7/zYRWykpZMnb/hGe0wzm7dyQRsNampV8vciPWcx8msYpiiEWhMSobd7fxl0+gGwV1CWNkgV5HqU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
