travis:
  secure:
    BINSTAR_TOKEN: JwqxLmNbLyN6MknMbc9FNhT1PfVN8eTHzMhtoyvhKf1DbTGO87VHOZc/DKsoXNxElXjx1/RPpbQX8ObWoLuXj1KaXH/H0I+IjmpZFttZAJms8cGxDtpeY6Oe+zNWfTCbBmzhsAUPI+lHmqowc3BcQcp/kndQIUbMQCVtrVJCwty/7QBX0YtIebgkxKQ3iEhUrf5qfq+l6gR8/jr56sk7Dmq/lF7ddj9UUr62pq7PPKXqjdF1V+iRMEmle5+YfwCskBiaz0BBIB4h/4jAZPjQnwvKk6sRM8kHShQv077hqViQhMi0cjLuNocosiOJa3ulJ1NscfJ9Zx65RYI7O4DkUZyaelZ5qIVgzNyQVGfkiyEYQ8l7tiSdN9HjSwrLXrsdPYlIj9wqmFI0YB7PsvnrQBMXh1CWT0tkuFCv90lQkiXNinjLSYNUpjIqSFbm9kpdK71AOKKrnBhLLpHmtD9usVjcwnMXwIThib0iXWuS7Aimg1Dz/ZgM3+o7goGEiiVW4o5rSeRNbSgep7LA04LLEuii3tWF8e6D8S9X7+AS6SWAhDNW9xqQ5ZWa87nAtgoOFXj2IsTSvebP6e68CSPbxRKyjEfAMbzkTKdj+B+06IEIaAWtZhqVeLH39887iEuGYOdJNPlDk0qhnlV2NS/vhIVtaGiJ+O4+FYYlAToYpKs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
